image: docker:18-git

services:
- docker:dind

# When using dind, it's wise to use the overlayfs driver for
# improve performance.
variables:
  DOCKER_DRIVER: overlay
  IMAGE_TAG_NAME: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_BRANCH
cache:
  key: "$CI_BUILD_REF"

stages:
- Deploy

before_script:
- export CONTAINER_TEST_IMAGE=$IMAGE_TAG_NAME:latest
- docker info
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
- git config --global user.email "thiago.soaresm19@gmail.com"
- git config --global user.name "GIT LAB CD SERVER"
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
- chmod 644 ~/.ssh/known_hosts

deploy_test:
  image: docker:git
  variables:
    APP_NAME: <CHANGE HERE>
    APP_ADDRESS: '<CHANGE HERE>'
  stage: Deploy
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME
    - git push dokku@$APP_ADDRESS:$APP_NAME $CI_COMMIT_REF_NAME:master
  only:
    - test


deploy_production:
  image: docker:git
  variables:
    APP_NAME: <CHANGE HERE>
    APP_ADDRESS: '<CHANGE HERE>'
  stage: Deploy
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME
    - git push dokku@$APP_ADDRESS:$APP_NAME $CI_COMMIT_REF_NAME:master
  only:
    - master