version: '3.8'
volumes:
  bundle_path:  # for rails gems
  cache: # cache for rails assets
services:
  redis:
    image: redis:6.2.6-alpine
    command: redis-server
    ports:
      - "6379:6379"
  db:
    image: postgres:14.2-alpine
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DATABASE=rails_base_development
       - POSTGRES_ROOT_PASSWORD=root
    ports:
      - "5432:5432"
  app:
    # use the Dockerfile next to this file
    build: .
    command: rails s -p 3000 -b '0.0.0.0' -e development
    stdin_open: true
    tty: true
    shm_size: '256mb'
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - NODE_ENV=development
    volumes:
      - .:/var/www/myapp
      - bundle_path:/bundle
      - cache:/cache
      # expose the port
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
      - redis