require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Admin::UsersController, type: :controller  do

  let(:valid_attributes) {
    attributes_for(:user)
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
    # {name: ""}
  }

  let(:user){ create(:user) }

  let(:user){ create(:user) }

  before(:each) do      
    sign_in user
  end 

  describe "GET #index" do
    it "assigns all users as @instances" do
      get :index, params: {}
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "assigns the requested users as @instance" do
      get :show, params: {:id => user.to_param}
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "assigns a new users as @instance" do
      get :new, params: {}
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "assigns the requested users as @instance" do
      get :edit, params: {:id => user.to_param}
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, params: {:user => valid_attributes}
        }.to change(User, :count).by(1)
      end

      it "redirects to the list of entities" do
        post :create, params: {:user => valid_attributes}
        expect(response).to redirect_to(admin_users_url)
      end
    end

    context "with invalid params" do

      it "re-renders the 'new' template" do
        post :create, params: {:user => invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
        # { name: "john"}
      }

      it "updates the requested user" do
        put :update, params: {:id => user.to_param, :user => new_attributes}
        user.reload
        skip("Add assertions for updated state")
        # expect(user.name).to eq "john" 
      end

      it "redirects to the user" do
        put :update, params: {:id => user.to_param, :user => valid_attributes}
        expect(response).to redirect_to(admin_user_path(user))
      end
    end

    context "with invalid params" do

      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: {:id => user.to_param, :user => invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested users" do
      user = create(:user)
      expect {
        delete :destroy, params: {:id => user.to_param}
      }.to change(User, :count).by(-1)
    end

    it "redirects to the users list" do
      delete :destroy, params: {:id => user.to_param}
      expect(response).to redirect_to(admin_users_url)
    end
  end

end
