# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.8
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION

# After create give the permission to user vscode to workdirectory folder
# chown -R vscode /workspaces/rails_lab